inputSet:
  identifier: "prod"
  pipeline:
    identifier: "CD"
    stages:
    - stage:
        identifier: "deploy"
        type: "Deployment"
        spec:
          service:
            serviceInputs:
              serviceDefinition:
                type: "Kubernetes"
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: "test"
                      sources:
                      - identifier: "test"
                        type: "Acr"
                        spec:
                          tag: ""
          environment:
            environmentRef: ""
            environmentInputs: ""
            serviceOverrideInputs: ""
            infrastructureDefinitions: ""
    - stage:
        identifier: "deploy_chart_list"
        type: "Deployment"
        spec:
          service:
            serviceInputs:
              serviceDefinition:
                type: "Kubernetes"
                spec:
                  manifests:
                  - manifest:
                      identifier: "nginx"
                      type: "HelmChart"
                      spec:
                        chartVersion: ""
                  artifacts:
                    primary:
                      primaryArtifactRef: "acr"
                      sources:
                      - identifier: "acr"
                        type: "Acr"
                        spec:
                          tag: ""
                          registry: "lorenprod"
          environment:
            environmentRef: "prod"
            infrastructureDefinitions: []
  name: "prod"
  orgIdentifier: "default"
  projectIdentifier: "technical_exercise"
